name: sonarqube

on:
  workflow_run:
    workflows:
      - lint-code
    types:
      - completed

  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  sonar-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out a copy of the repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set vars to github
        run: |
          echo "APP_TAG=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV
          echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" >> $GITHUB_ENV
          echo "SONAR_LOGIN=${{ secrets.SONAR_LOGIN }}" >> $GITHUB_ENV

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Check dependences
        run: task sonar:check

      - name: Scan Sonar
        run: task sonar:scan
