name: sonarqube

on:
  workflow_run:
    workflows:
      - lint-code
    types:
      - completed

  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  sonar-scan:
    runs-on: ubuntu-20.04
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}

    steps:
      - name: Check out a copy of the repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Scan Sonar
        if: ${{ !env.ACT }}
        run: |-
          docker run --rm -v $(pwd)/:/usr/src \
          -e SONAR_HOST_URL=$SONAR_HOST_URL \
          -e SONAR_LOGIN=$SONAR_LOGIN \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner
